### PR TITLE
add support for AlmaLinux & Rocky

### PR DESCRIPTION
**Pull request by jhoblitt**
Manually tested as working on an AlmaLinux 8.6 instance.

### CODE REVIEW

**Comment by trevor-vaughan** [comment]
@jhoblitt Added updates as a PR.

**Comment by trevor-vaughan** [comment]
Needs simp/pupmod-simp-dconf#35

**Comment by trevor-vaughan** [comment]
I'm going to go ahead and merge this with the RELENG checks failing and push an additional PR with the necessary release adjustments.

The tests have passed locally without issue.

**Comment by jhoblitt** [comment]
Woot! Thank you.

**Pull request merged**
